version: '3.3'

services:
  app:
    image: meal-front
    container_name: meal-front
    build: .
    restart: always
    ports:
      - 80:3000
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    environment:
      - PUBLIC_URL=jandaya
      - REACT_APP_API_URL=http://localhost:3333
      - REACT_APP_TIME_LIMIT_MORNING=15
      - REACT_APP_TIME_LIMIT_AFTERNOON=17
      - REACT_APP_TIME_LIMIT_NIGHT=21
    volumes:
      - .:/usr/app
      - /usr/app/node_modules/